format_version: 10
pipelines:
  cRIO_FPGA_Main:
    group: cRIO
    parameters:
      GIT_DIR: Chakraborty_cRIO
      LV_VERSION: '2019'
      FPGA_TARGET_NAME: FPGA Target
      FPGA_BUILDSPEC_NAME: FPGA Main
      PROJECT_PATH: Chakraborty_cRIO\cRIO-9045-RT.lvproj
      VERSION_VI_PATH: FPGA/FPGA Version Number.vi
    materials:
      Chakraborty_cRIO:
        git: git@github.com:oist/Chakraborty_cRIO
        destination: Chakraborty_cRIO
        auto_update: false
        shallow_clone: false
    stages:
    - build_fpga:
        fetch_materials: 'yes'
        clean_workspace: 'yes'
        approval: manual
        jobs:
          build_fpga:
            timeout: 90
            elastic_profile_id: labview_2019_x86_fpga
            artifacts:
            - build:
                source: FPGA Bitfiles/*.lvbitx
                destination: FPGA Bitfiles
            tasks:
            - &id001
              exec:
                run_if: passed
                command: powershell
                arguments:
                - -Command
                - New-Item
                - -Force
                - -ItemType
                - Directory
                - -Path
                - \"C:\LabVIEW Sources\PPLs\"
            - &id002
              exec:
                run_if: passed
                command: ls
                arguments:
                - '*'
            - &id003
              exec:
                run_if: passed
                command: powershell
                arguments:
                - -Command
                - Get-ChildItem
                - -Recurse
                - -Depth
                - '1'
            - &id004
              exec:
                run_if: passed
                command: g-cli
                arguments:
                - --lv-ver
                - '#{LV_VERSION}'
                - --verbose
                - '#{GIT_DIR}\Builder\Script_FPGA_Version_VI_Wrapper.vi'
                - --
                - '#{VERSION_VI_PATH}'
            - &id005
              exec:
                run_if: passed
                command: LabVIEWCLI.exe
                arguments:
                - -OperationName
                - ExecuteBuildSpec
                - -Verbosity
                - Detailed
                - -ProjectPath
                - '#{PROJECT_PATH}'
                - -TargetName
                - '#{FPGA_TARGET_NAME}'
                - -BuildSpecName
                - '#{FPGA_BUILDSPEC_NAME}'
  cRIO_FPGA_Expansion:
    group: cRIO
    parameters:
      GIT_DIR: Chakraborty_cRIO
      LV_VERSION: '2019'
      FPGA_TARGET_NAME: FPGA Target 2
      FPGA_BUILDSPEC_NAME: Main
      PROJECT_PATH: Chakraborty_cRIO\cRIO-9045-RT.lvproj
      VERSION_VI_PATH: FPGA Expansion/FPGA Expansion Version Number.vi
    materials:
      Chakraborty_cRIO:
        git: git@github.com:oist/Chakraborty_cRIO
        destination: Chakraborty_cRIO
        auto_update: false
        shallow_clone: false
    stages:
    - build_fpga:
        fetch_materials: 'yes'
        clean_workspace: 'yes'
        approval: manual
        jobs:
          build_fpga:
            timeout: 90
            elastic_profile_id: labview_2019_x86_fpga
            artifacts:
            - build:
                source: FPGA Bitfiles/*.lvbitx
                destination: FPGA Bitfiles
            tasks:
            - *id001
            - *id002
            - *id003
            - *id004
            - *id005
