format_version: 10
pipelines:
  Zip_PPL_Builder:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      source_repo:
        git: git@github.com:oist/Chakraborty_PPL-Builder
        shallow_clone: true
        auto_update: false
        branch: NIPKG_Builds
        destination: PPL_Builder
    stages:
    - Zip:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Zip:
            timeout: 0
            tasks:
            - exec:
                command: powershell
                arguments:
                - -Command
                - Compress-Archive
                - -Path
                - PPL_Builder
                - -DestinationPath
                - PPL_Builder.zip
                run_if: passed
            artifacts:
            - build:
                source: PPL_Builder.zip
                destination: PPL_Builder
