from enum import Enum

# Simple constants
via_plugin_version = "0.2.2.3"

# Names defined in the Zip_PPL_Builder config file
zipPipelineName = "Zip_PPL_Builder"
zipPipelineStageName = "Zip"
zipPipelineJobName = "Zip"

builderMaterial = {
    "pipeline": zipPipelineName,
    "stage": zipPipelineStageName,
    "ignore_for_scheduling": True,
}


class Target(Enum):
    Windows_32_Release = 0
    Windows_32_Debug = 1
    Windows_64_Release = 2
    Windows_64_Debug = 3
    cRIO_Release = 4
    cRIO_Debug = 5
    FPGA_Release = 6
    FPGA_Debug = 7


# The names here are used for the G-CLI call directly.
class BuildType(Enum):
    MAJOR = 0
    MINOR = 1
    PATCH = 2
    BUILD = 3


targetPathEnds = {
    "Windows_32_Release": "Windows\\Release_32",
    "Windows_32_Debug": "Windows\\Debug_32",
    "Windows_64_Release": "Windows\\Release_64",
    "Windows_64_Debug": "Windows\\Debug_64",
    "cRIO_Release": "cRIO-9045\\Release_32\\home\\lvuser\\natinst\\bin",
    "cRIO_Debug": "cRIO-9045\\Debug_32\\home\\lvuser\\natinst\\bin",
    "cRIO_Release": "cRIO-9045\\Release_32\\home\\lvuser\\natinst\\bin",
    "cRIO_Debug": "cRIO-9045\\Debug_32\\home\\lvuser\\natinst\\bin",
    "FPGA_Release": "cRIO-9045\\Release_32\\home\\lvuser\\natinst\\bin",
    "FPGA_Debug": "cRIO-9045\\Debug_32\\home\\lvuser\\natinst\\bin",
}

profileId = {
    "2019": {
        Target.Windows_32_Debug: "labview_2019_x86",
        Target.Windows_32_Release: "labview_2019_x86",
        Target.Windows_64_Debug: "labview_2019_x64",
        Target.Windows_64_Release: "labview_2019_x64",
        Target.cRIO_Debug: "labview_2019_x86_crio",
        Target.cRIO_Release: "labview_2019_x86_crio",
        Target.FPGA_Debug: "labview_2019_x86_fpga",
        Target.FPGA_Release: "labview_2019_x86_fpga",
    },
    "2021": {
        Target.Windows_32_Debug: "labview_2021_x86",
        Target.Windows_32_Release: "labview_2021_x86",
        Target.Windows_64_Debug: "labview_2021_x64",
        Target.Windows_64_Release: "labview_2021_x64",
        Target.cRIO_Debug: "labview_2021_x86_crio",
        Target.cRIO_Release: "labview_2021_x86_crio",
        Target.FPGA_Debug: "labview_2021_x86_fpga",
        Target.FPGA_Release: "labview_2021_x86_fpga",
    },
}

labviewDir = {
    "2019": {
        Target.Windows_32_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
        Target.Windows_32_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
        Target.Windows_64_Debug: "C:\\Program Files\\National Instruments\\LabVIEW 2019",
        Target.Windows_64_Release: "C:\\Program Files\\National Instruments\\LabVIEW 2019",
        Target.cRIO_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
        Target.cRIO_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
        Target.FPGA_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
        Target.FPGA_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2019",
    },
    "2021": {
        Target.Windows_32_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
        Target.Windows_32_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
        Target.Windows_64_Debug: "C:\\Program Files\\National Instruments\\LabVIEW 2021",
        Target.Windows_64_Release: "C:\\Program Files\\National Instruments\\LabVIEW 2021",
        Target.cRIO_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
        Target.cRIO_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
        Target.FPGA_Debug: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
        Target.FPGA_Release: "C:\\Program Files (x86)\\National Instruments\\LabVIEW 2021",
    },
}

# -- Configuration for the NIPKG Fetch Artifact step -- #
# DownloadOrInstall
# --
# SuppressIncompatibilityErrors
# AllowUpgrade (default on)
# AllowDowngrade
# AllowUninstallation
# InstallRecommended
# InstallRootDir (only applies to packages with "Plugin: relative-file" attribute)
# --
# DownloadDestDir
# DownloadIncludeDeps
# DownloadSkipDependenciesCheck
fetch_ppl_configuration = {
    "options": {
        "DownloadOrInstall": "Install",
        "SuppressIncompatibilityErrors": False,
        "AllowUpgrade": True,
        "AllowDowngrade": True,
        "AllowUninstallation": False,
        "InstallRecommended": False,
        "InstallRootDir": None,
    }
}

# ------------------- Jobs ---------------------------- #
dir_job = {"tasks": [{"exec": {"command": "dir", "arguments": ["*"]}}]}

via_job = {
    "environment_variables": {"PROJECT_TITLE": "#{PPL_Name}"},
    "timeout": 3,
    "tabs": {
        "VIA_Results": "#{PPL_Name}/viaResultsCheckstyle.xml",
        "VIA_Report": "#{PPL_Name}/CheckstyleReport.html",
    },
    "artifacts": [
        # Checkstyle xml generated by LabVIEW code
        {
            "build": {
                "source": "#{GIT_DIR}/viaResultsCheckstyle.xml",
                "destination": "#{PPL_Name}",
            }
        },
        # Report generated by plugin - the main tab for this job
        {"build": {"source": "CheckstyleReport.html", "destination": "#{PPL_Name}"}},
        # The raw VIA results (could remove)
        {
            "build": {
                "source": "#{GIT_DIR}/viaResults.xml",
                "destination": "#{PPL_Name}",
            }
        },
    ],
    "tasks": [
        {
            "exec": {
                "run_if": "passed",
                "command": "g-cli",
                "working_directory": "#{GIT_DIR}",
                "arguments": [
                    "--verbose",
                    "--lv-ver",
                    "#{LV_VERSION}",
                    "viaRunner.vi",
                    "--",
                    "viaResults.xml",
                ],
            }
        },
        {
            "plugin": {
                "configuration": {
                    "id": "Checkstyle.LabVIEW.VIA",
                    "version": via_plugin_version,
                },
                "run_if": "passed",
                "options": {
                    "SourceVIAFile": "#{GIT_DIR}/viaResults.xml",
                    "SourceCheckstyleFile": "#{GIT_DIR}/viaResultsCheckstyle.xml",
                    "DestinationFile": "CheckstyleReport.html",
                    "AddEmpty": False,
                },
            }
        },
    ],
}

# ------------------- Tasks --------------------------- #
create_ppl_dir = {
    "exec": {
        "run_if": "passed",
        "command": "powershell",
        "arguments": [
            "-Command",
            "New-Item",
            "-Force",
            "-ItemType",
            "Directory",
            "-Path",
            '\\"C:\\LabVIEW Sources\\PPLs\\"',
        ],
    }
}

ls_task = {"exec": {"run_if": "passed", "command": "ls", "arguments": ["*"]}}

# Note that adding a '*' to the end here causes an error
# This seems to be due to the execution via Invoke-Expression and the $RUN_CMD variable in the elastic agent.
ls_currentDir_task = {
    "exec": {"run_if": "passed", "command": "ls", "arguments": ["PPLs\\\\Current"]}
}

gci_recurse_1_task = {
    "exec": {
        "run_if": "passed",
        "command": "powershell",
        "arguments": [
            "-Command",
            "Get-ChildItem",
            "-Recurse",
            "-Depth",
            "1",
        ],
    }
}

gci_recurse_task = {
    "exec": {
        "run_if": "passed",
        "command": "powershell",
        "arguments": ["-Command", "Get-ChildItem", "-Recurse"],
    }
}

find_files_task = {
    "exec": {
        "run_if": "any",
        "command": "find",
        "arguments": [".", "-type", "f"],
    }
}

fetch_builder_task = {
    "fetch": {
        "run_if": "passed",
        "pipeline": zipPipelineName,
        "stage": zipPipelineStageName,
        "job": zipPipelineJobName,
        "source": "PPL_Builder/PPL_Builder.zip",
        "destination": ".",
        "is_file": "yes",
    }
}

expand_builder_task = {
    "exec": {
        "run_if": "passed",
        "command": "powershell",
        "arguments": [
            "-Command",
            "Expand-Archive",
            "-Path",
            "PPL_Builder.zip",
            "-DestinationPath",
            ".",
        ],
    }
}

gcli_build_task = {
    "exec": {
        "run_if": "passed",
        "command": "g-cli",
        "arguments": [
            "--lv-ver",
            "#{LV_VERSION}",
            "%BITNESS_FLAG%",
            "PPL_Builder\\Call_Builder_Wiresmith.vi",  # This must be a backward slash
            "--",
            "#{PPL_LIB_PATH}",
            "PPLs/Current",
            "%IS_DEBUG_BUILD%",
            "%TARGET_SYSTEM%",
            "%BUILD_TYPE%",
            "#{Dependency_PPL_Names}",
        ],
    }
}

rt_publish_to_feed_stage = {
    "fetch_materials": "no",
    "clean_workspace": "yes",
    "approval": "success",
    "jobs": {
        "publish_to_feed": {
            "resources": ["linux"],
            "timeout": 5,
            "tasks": [
                {
                    "fetch": {
                        "run_if": "passed",
                        "stage": "build",
                        "job": "build_debug",
                        "source": "#{APP_NAME}_debug",
                        "is_file": False,
                        "destination": "artifacts",
                    }
                },
                {
                    "fetch": {
                        "run_if": "passed",
                        "stage": "build",
                        "job": "build_release",
                        "source": "#{APP_NAME}_release",
                        "is_file": False,
                        "destination": "artifacts",
                    }
                },
                find_files_task,
                {
                    "exec": {
                        "run_if": "passed",
                        "command": "bash",
                        "arguments": [
                            "-lc",
                            # /packages (not e.g. /var/www/pkgupload/packages) because the user is chrooted.
                            (
                                "scp -i ${PACKAGE_SERVER_UPLOAD_KEY} "
                                "artifacts/#{APP_NAME}_*/*.ipk "
                                "${PACKAGE_SERVER_UPLOAD_USER}@${PACKAGE_SERVER}:/packages/"
                            ),
                        ],
                    }
                },
                {
                    "exec": {
                        "run_if": "passed",
                        "command": "bash",
                        "arguments": [
                            "-lc",
                            (
                                "ssh -Ti ${PACKAGE_SERVER_REFRESH_KEY} "
                                "${PACKAGE_SERVER_REFRESH_USER}@${PACKAGE_SERVER}"
                            ),
                            # No need for a command - the user is bound to a single command which will execute on connection.
                        ],
                    }
                },
                {
                    "exec": {
                        "run_if": "passed",
                        "command": "bash",
                        "arguments": [
                            "-lc",
                            (
                                "set -euo pipefail; "
                                'IPK="$(ls -1 artifacts/#{APP_NAME}_release/*.ipk | head -n1)"; '
                                'BASE="$(basename "$IPK" .ipk)"; '
                                "BUILD_VER_RAW=\"$(printf '%s\\n' \"$BASE\" | sed -E 's/^.*_([^_]*)_[^_]*$/\\1/')\"; "
                                "BUILD_VER=\"$(printf '%s\\n' \"$BUILD_VER_RAW\" | sed -E 's/^(.*)-([^-]+)$/\\1.\\2/')\"; "
                                "PT='#{PRERELEASE_TAG}'; "
                                'TAG="RT-v${BUILD_VER}${PT:+-${PT}}"; '
                                'REPO_URL="${GO_MATERIAL_URL_CHAKRABORTY_CRIO:?GO_MATERIAL_URL_CHAKRABORTY_CRIO is required}"; '
                                'REV="${GO_REVISION_CHAKRABORTY_CRIO:?GO_REVISION_CHAKRABORTY_CRIO is required}"; '
                                'WORKDIR="$(mktemp -d)"; '
                                'trap "rm -rf ${WORKDIR}" EXIT; '
                                'git -C "$WORKDIR" init -q; '
                                'git -C "$WORKDIR" remote add origin "$REPO_URL"; '
                                'git -C "$WORKDIR" fetch --depth=1 origin "$REV"; '
                                'git -C "$WORKDIR" tag -a "$TAG" "$REV" -m "RT build $TAG"; '
                                'git -C "$WORKDIR" push origin "$TAG"'
                            ),
                        ],
                    }
                },
            ],
        }
    },
}

rt_deploy_stage = {
    "fetch_materials": "no",
    "clean_workspace": "yes",
    "approval": "manual",  # Manual approval before deployment
    "jobs": {
        "deploy_to_crio": {
            "resources": ["linux"],
            "timeout": 5,
            "tasks": [
                {
                    "fetch": {
                        "run_if": "passed",
                        "stage": "build",
                        "job": "build_#{DEPLOY_BUILD_TYPE}",
                        "source": "#{APP_NAME}_#{DEPLOY_BUILD_TYPE}",
                        "destination": "artifacts",
                    }
                },
                find_files_task,
                {
                    "exec": {
                        "run_if": "passed",
                        "command": "bash",
                        "arguments": [
                            "-lc",
                            (
                                'IPK="$(ls -1 artifacts/*.ipk | head -n1)"; '
                                'BASE="$(basename "$IPK" .ipk)"; '
                                "PKG_NAME=\"$(printf '%s\\n' \"$BASE\" | sed -E 's/_[^_]*_[^_]*$//')\"; "
                                "PKG_VER=\"$(printf '%s\\n' \"$BASE\" | sed -E 's/^.*_([^_]*)_[^_]*$/\\1/')\"; "
                                'echo "Deploying ${PKG_NAME}=${PKG_VER} from feed"; '
                                'sshpass -p "{{SECRET:[secrets.json][crio_ssh_password]}}" '
                                "ssh -o StrictHostKeyChecking=no ${CRIO_USER}@${CRIO_HOST} "
                                '"opkg update && opkg remove ${PKG_NAME} || true; opkg install ${PKG_NAME}=${PKG_VER}"'
                            ),
                        ],
                    }
                },
                {
                    "exec": {
                        # This may need redirection through bash to correctly set the CRIO_USER and CRIO_HOST
                        "run_if": "passed",
                        "command": "sshpass",
                        "arguments": [
                            "-p",
                            "{{SECRET:[secrets.json][crio_ssh_password]}}",
                            "ssh",
                            "-o",
                            "StrictHostKeyChecking=no",
                            "${CRIO_USER}@${CRIO_HOST}",
                            "reboot",
                        ],
                    }
                },
            ],
        }
    },
}

# ------------------- FPGA Build Tasks -------------------- #
fpga_build_task = {
    "exec": {
        "run_if": "passed",
        "command": "LabVIEWCLI.exe",
        "arguments": [
            "-OperationName",
            "ExecuteBuildSpec",
            "-Verbosity",
            "Detailed",
            "-ProjectPath",
            '"$PWD\\#{PROJECT_PATH}"',
            "-TargetName",
            "#{FPGA_TARGET_NAME}",
            "-BuildSpecName",
            "#{FPGA_BUILDSPEC_NAME}",
        ],
    }
}

fpga_artifact_path = "FPGA Bitfiles/*.lvbitx"

script_fpga_version_task = {
    "exec": {
        "run_if": "passed",
        "command": "g-cli",
        "arguments": [
            "--lv-ver",
            "#{LV_VERSION}",
            "--verbose",
            "Builder\\Script_FPGA_Version_VI_Wrapper.vi",
            "--",
            "#{VERSION_VI_PATH}",
        ],
        "working_directory": "#{GIT_DIR}",
    }
}

# ------------------- RT Build with G-CLI ----------------- #
gcli_rt_build_task = {
    "exec": {
        "run_if": "passed",
        "command": "g-cli",
        "arguments": [
            "--lv-ver",
            "#{LV_VERSION}",
            "--verbose",
            "Builder\\Build_RT_Application.vi",
            "--",
            "cRIO-9045-RT.lvproj",
            "RT CompactRIO Target",
            "RT Main Application",
            "%BUILD_TYPE%",
            "%IS_DEBUG_BUILD%",
            "#{Dependency_PPL_Names}",
        ],
        "working_directory": "#{GIT_DIR}",
    }
}
